export const eightBallMessages = [
  'Yes',
  'No',
  'Certainly',
  'Signs point to yes',
  'Probably not',
  'Doubtful',
  'Yes definitely',
  'You may rely on it',
  'Concentrate and ask again',
  "I don't know",
  'It is undecidedly so',
  'Unsure',
  'My reply is no',
  'Cannot predict now',
  'My sources say no',
  'My sources say yes',
  'My reply is yes',
  'You cannot rely on it',
];
